export const SET_PLAID_STATE = "SET_PLAID_STATE";

export const SET_PLAID_PAYMENT_STATE = "SET_PLAID_PAYMENT_STATE";

export const SET_PLAID_AUTH_STATE = "SET_PLAID_AUTH_STATE";

export const SET_PLAID_TRANSACTIONS_STATE = "SET_PLAID_TRANSACTIONS_STATE";

export const SET_PLAID_IDENTITY_STATE = "SET_PLAID_IDENTITY_STATE";

export const SET_PLAID_ASSETS_STATE = "SET_PLAID_ASSETS_STATE";

export const SET_PLAID_BALANCE_STATE = "SET_PLAID_BALANCE_STATE";

export const SET_PLAID_HOLDING_STATE = "SET_PLAID_HOLDING_STATE";

export const SET_PLAID_INVEST_TRANSACTIONS_STATE =
	"SET_PLAID_INVEST_TRANSACTIONS_STATE";

export const SET_PLAID_LIABILITIES_STATE = "SET_PLAID_LIABILITIES_STATE";

export const SET_PLAID_TRANSFER_STATE = "SET_PLAID_TRANSFER_STATE";

export const SET_PLAID_ACCOUNTS_STATE = "SET_PLAID_ACCOUNTS_STATE";

export const SET_PLAID_CATEGORY_STATE = "SET_PLAID_CATEGORY_STATE";
