export const SET_USER_INFO = "SET_USER_INFO";

export const DELETE_ITEM_BY_ID = "DELETE_ITEM_BY_ID";

export const UPDATE_USER_INFO = "UPDATE_USER_INFO";

export const SET_DASHBOARD_DATA = "SET_DASHBOARD_DATA";

export const SET_ANNUAL_TRANSACTION = "SET_ANNUAL_TRANSACTION";

export const SET_DASHBOARD_AI_SUMMARY = "SET_DASHBOARD_AI_SUMMARY";

export const SET_ANALYZE_AI_SUMMARY = "SET_ANALYZE_AI_SUMMARY";

export const SET_ANALYZE_FILTER_DATE = "SET_ANALYZE_FILTER_DATE";

export const SET_SELECTED_ACCOUNTS = "SET_SELECTED_ACCOUNTS";
